updated codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -39,8 +39,30 @@ workflows:
             echo "Error: PROVISIONING_PROFILE is not set."
             exit 1
           fi
-          echo "$PROVISIONING_PROFILE" > $CM_BUILD_DIR/ios/provisioning_profile.txt
-          base64 --decode $CM_BUILD_DIR/ios/provisioning_profile.txt > $CM_BUILD_DIR/ios/YourProfile.mobileprovision
+
+          # Ensure the file path is correct
+          profile_path="$CM_BUILD_DIR/ios/provisioning_profile.txt"
+          output_path="$CM_BUILD_DIR/ios/YourProfile.mobileprovision"
+
+          # Save the Base64 string to a file
+          echo "$PROVISIONING_PROFILE" > "$profile_path"
+
+          # Validate the Base64 string
+          if ! base64 -d "$profile_path" > /dev/null 2>&1; then
+            echo "Error: The provided PROVISIONING_PROFILE is not a valid Base64 string."
+            exit 1
+          fi
+
+          # Decode the Base64 string to the provisioning profile
+          base64 --decode "$profile_path" > "$output_path"
+    
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to decode the provisioning profile."
+           exit 1
+          fi
+
+          echo "Provisioning profile saved to $output_path"
+
       - name: Verify Provisioning Profile
         script: |
           if [ ! -f "$CM_BUILD_DIR/ios/YourProfile.mobileprovision" ]; then
