updated codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -33,14 +33,34 @@ workflows:
         script: cd ios && pod install && cd ..
       - name: Bundle React Native assets
         script: npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
-      - name: Save Base64 Content
+            - name: Save Base64 Content
         script: |
+          # Verifica se a variável PROVISIONING_PROFILE_BASE64 está definida e não vazia
           if [ -z "$PROVISIONING_PROFILE_BASE64" ]; then
-            echo "Error: PROVISIONING_PROFILE_BASE64 is not set."
+            echo "Error: PROVISIONING_PROFILE_BASE64 is not set or is empty."
             exit 1
           fi
+          
+          # Salva o conteúdo da variável em um arquivo
           echo "$PROVISIONING_PROFILE_BASE64" > $CM_BUILD_DIR/ios/provisioning_profile_base64.txt
-          base64 --decode $CM_BUILD_DIR/ios/provisioning_profile_base64.txt > $CM_BUILD_DIR/ios/YourProfile.mobileprovision
+          
+          # Verifica se o arquivo foi criado e não está vazio
+          if [ ! -s "$CM_BUILD_DIR/ios/provisioning_profile_base64.txt" ]; then
+            echo "Error: provisioning_profile_base64.txt is not created or is empty."
+            exit 1
+          fi
+
+          # Decodifica o arquivo base64 para .mobileprovision
+          if ! base64 --decode $CM_BUILD_DIR/ios/provisioning_profile_base64.txt > $CM_BUILD_DIR/ios/YourProfile.mobileprovision; then
+            echo "Error: Failed to decode base64 content."
+            exit 1
+          fi
+          
+          # Verifica se o arquivo .mobileprovision foi criado e não está vazio
+          if [ ! -s "$CM_BUILD_DIR/ios/YourProfile.mobileprovision" ]; then
+            echo "Error: YourProfile.mobileprovision is not created or is empty."
+            exit 1
+          fi
       - name: Verify Provisioning Profile
         script: |
           if [ ! -f "$CM_BUILD_DIR/ios/YourProfile.mobileprovision" ]; then
